main/urls.py
from django.urls import path
# self edited --------------------------
from django.urls import re_path
from django.views.static import serve
from mysite.settings import MEDIA_ROOT
# self edited --------------------------
from main.views import ai_solutions
from main.views.consulting import HomeView
from main.views.consulting import PostDetail
from main.views.consulting import CreatePost
from main.views.consulting import AddComment,shopping_carts
from main.views.consulting import Experts
from main.views.consulting import LikeView
from main.views.consulting import PostRate
from main.views.consulting import ReverseView
from main.views.consulting import SortedView
from main.views.consulting import HotView
from main.views.consulting import MyShare
from main.views.plant import *
from main.views.plant import my_plants
from main.views.plant import add_plants, manage_plants
from main.views.plant import diagnoseView
from main.views.plant import delete_plants
from main.views.payment import checkout
from main.views.payment import create_alipay_payment_intent
from main.views.payment import create_wechat_pay_payment_intent
from main.views.payment import success
from main.views.payment import cancel
from main.views import payment
from main.views.cart import view_cart
from main.views.cart import add_to_cart

app_name = 'main'
urlpatterns = [
    path('', ai_solutions.index, name='index'),
    path('aisolutions/<int:page>/', ai_solutions.ai_solutions, name='ai_solutions'),
    path('aisolutions/smartcurtain/<int:page>/', ai_solutions.smart_curtain, name='smart_curtain'),
    path('aisolutions/ai_classification/', ai_solutions.ai_classification, name='ai_classification'),
    path('aisolutions/aidiseasediagnose/', ai_solutions.ai_disease_diagnose, name='aidiseasediagnose'),
    path('aisolutions/aidiseasediagnose/pichandle_classification/', ai_solutions.pic_handle_classification, name='pichandle_classification'),
    path('aisolutions/aidiseasediagnose/pichandle_yolov5/', ai_solutions.pic_handle_yolov5, name='pichandle_yolov5'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': 'main/static/'}),

    path('aisolutions/virtualrealityforesttherapy/<int:page>/', ai_solutions.virtual_reality_forest_therapy, name='virtual_reality_forest_therapy'),
    path('aisolutions/virtualrealityforesttherapy/digital_twin/', ai_solutions.digital_twin, name='digital_twin'),
    path('aisolutions/virtualrealityforesttherapy/vr_detail/', ai_solutions.vr_detail, name='vr_detail'),


    #path('', HomeView.as_view(), name='index'),
    path('consulting/', HomeView.as_view(), name='consulting'),
    path('consulting/my_share', MyShare.as_view(), name='my_share'),
    path('consulting/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('consulting/creatingPost/', CreatePost.as_view(), name='create_post'),
    path('consulting/<int:pk>/commentPost/', AddComment.as_view(), name='add_comment'),
    path('consulting/experts', Experts.as_view(), name='experts'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('consulting/', ReverseView.as_view(), name='reverse_post'),
    path('consulting/sorted/', SortedView.as_view(), name='sorted_post'),
    path('consulting/hot/', HotView.as_view(), name='hot_post'),
    path('my_plants/', my_plants.as_view(), name='my_plants'),
    path('manage_plants/<int:pk>/', manage_plants.as_view(), name='manage_plants'),
    path('add_plants/', add_plants.as_view(), name='add_plants'),
    path('plants_care/<int:pk>', plants_care.as_view(), name='plants_care'),
    path('diagnose/<int:pk>', diagnoseView, name='diagnose'),
    path('delete_plants/<int:pk>', delete_plants.as_view(), name='delete_plants'),
    path('shopping_carts/', shopping_carts.as_view(), name='shopping_carts'),


    path('consulting/<int:post_id>/<int:rating>/', PostRate, name='post_rate'),
    path("checkout/", checkout, name="checkout"),
    path("checkout/create_wechat_pay_payment_intent", payment.create_wechat_pay_payment_intent, name="create_wechat_pay_payment_intent"),
    path("checkout/create_alipay_payment_intent", payment.create_alipay_payment_intent, name="create_alipay_payment_intent"),
	  path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('cart/', view_cart, name='veiw_cart'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                path('', include('main.urls')),
                path('authentication/', include('authentication.urls')),
                path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views/ai_solutions.py
from django.shortcuts import render
# self edited --------------------------
from django.conf import settings
import main.views.yolov5_optimized.detect as detect
from pathlib import Path
# self edited --------------------------

import logging

# for 3rd party AI classification API
import json
import requests
import time

from authentication.utils.check_login_state import check_login
from main.utils.ai_solutions_utils import *

logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'main/index.html')


#@check_login
def ai_solutions(request, page):
    product_list, promotion_product_list, first_promotion_product, pagination = get_product(page)

    return render(request, 'main/ai_solutions.html',
                  {'product_list': product_list, 'promotion_product_list': promotion_product_list,
                   'first_promotion_product': first_promotion_product,
                   'promotion_product_num': range(len(promotion_product_list)),
                   'pagination': pagination})

#@check_login
def ai_classification(request):
    return render(request, 'main/ai_classification.html', {"success": True, "initial": True})

#@check_login
def ai_disease_diagnose(request):
    return render(request, 'main/ai_disease_diagnose.html', {"success": True, "initial": True})

def pic_handle_classification(request):
    diseases = []
    have_result = False
    
    if request.method == "POST":
        f1 = request.FILES.get('pic')
        if f1:
            fname = settings.MEDIA_ROOT + '/ai_classification/' + f1.name
            with open(fname,'wb') as pic:
                for c in f1.chunks():
                    pic.write(c)
            try:
                response_inference = json.loads(
                    requests.post(
                        "https://api.modelplace.ai/v3/process",
                        params={"model_id": 15, },
                        files={"upload_data": open(fname, "rb")}
                    ).content
                )
                
                while True:
                    response_task = json.loads(
                        requests.get(
                            "https://api.modelplace.ai/v3/task",
                            params=response_inference
                        ).content
                    )
                    if len(response_task) == 0:
                        raise Exception("response empty!")
                    
                    if response_task.get("status", -1) == -1:
                        raise Exception("Error: Error when detecting your image! This may result from the inaccessibility of our sevice, try again later!")
                    
                    if response_task["status"] != "finished":
                        time.sleep(5)
                    else:
                        res = response_task["result"]
                        for i in range(len(res)):
                            diseases.append(res[i]["class_name"])
                        have_result = True
                        return render(request,'main/ai_classification.html', {'success':True, 'result_list': diseases, 'have_result': have_result, 'userimg': f1.name})
            except Exception as e:
                return render(request,'main/ai_classification.html', {'success':False, "err_msg": str(e), 'userimg': f1.name})
        else:
            return render(request,'main/ai_classification.html', {'success':False, "err_msg": "Error: file uploaded is empty! Please click choose file to select an image!"})
        
    return render(request,'main/ai_classification.html', {'success':True, 'result_list': diseases, 'have_result': have_result})

def pic_handle_yolov5(request):
    if request.method == "POST":
        f1 = request.FILES.get('pic')
        if f1:
            fname = settings.MEDIA_ROOT + '/aidiseasediagnose/' + f1.name
            with open(fname,'wb') as pic:
                for c in f1.chunks():
                    pic.write(c)
            try:
                if "shallow" in request.POST:
                    result_path = detect.run(weights="main/views/yolov5_optimized/16x2.pt",imgsz=(416,416),conf_thres=0.5,source=fname)
                else:
                    result_path = detect.run(weights="main/views/yolov5_optimized/16x2.pt",imgsz=(416,416),conf_thres=0.25,source=fname)
            except Exception as e:
                return render(request,'main/ai_disease_diagnose.html', {'success':False, 'err_msg': repr(e)})
        else:
            error = "file uploaded is empty"
            return render(request,'main/ai_disease_diagnose.html', {'success':False, 'err_msg': error})

        # success
        txt_path = settings.MEDIA_ROOT + "/" + result_path + "/labels/result.txt"
        path = Path(txt_path)
        diseases = []
        have_result = False
        if path.is_file():
            have_result = True
            with open (txt_path, 'r') as f:
                for line in f.readlines():
                    disease = line.split(' ')[0]
                    if disease not in diseases:
                        diseases.append(disease)

        return render(request,'main/ai_disease_diagnose.html', {'success': True, 'result_path': result_path + "/result.jpg", 'result_list': diseases, 'have_result': have_result})

    return render(request,'main/ai_disease_diagnose.html', {'success': True})
# self edited --------------------------

#@check_login
def smart_curtain(request, page):
    product_list, promotion_product_list, first_promotion_product, pagination = get_product(page)
    load_animation = False
    if page == 1:
        load_animation = True

    return render(request, 'main/smart_curtain.html',
                  {'product_list': product_list,
                   'pagination': pagination,
                   'load_animation': load_animation})

#@check_login
def virtual_reality_forest_therapy(request, page):
    product_list, VR_product_list, first_promotion_product, pagination = get_VR_FT(page)

    return render(request, 'main/virtual_reality_forest_therapy.html',
                  {'product_list': product_list, 'VR_product_list': VR_product_list,
                   'first_promotion_product': first_promotion_product,
                   'promotion_product_num': range(len(VR_product_list)),
                   'pagination': pagination})

def digital_twin(request):
    return render(request,'main/VRFT_digital_twin.html')

def vr_detail(request):
    return render(request,'main/vr_detail.html')

main/views/cart.py
from django.shortcuts import render, get_object_or_404
from main.models import Product
from django.shortcuts import redirect
from main.models import Cart, CartItem
from authentication.models import User

def view_cart(request):
    user = request.user
    #user = get_object_or_404(User, pk=request.session['user_id'])
    cart, created = Cart.objects.get_or_create(user=user, ordered=False)

    cart_items = CartItem.objects.filter(cart=cart)

    return render(request, 'main/cart.html', {
        'cart_items': cart_items,
        'cart': cart,
    })


def add_to_cart(request, slug):
    user = request.user
    #user = get_object_or_404(User, pk=request.session['user_id'])
    cart, created = Cart.objects.get_or_create(user=user, ordered=False)
    product = get_object_or_404(Product, pk=product_id)

    # 查看购物车中是否已存在该商品
    cart_item, created = CartItem.objects.get_or_create(
        user=user,
        product=product,
        cart=cart,
    )

    if created:
        cart_item.price = product.price  # 如果是新创建的购物车项，设置价格
    else:
        cart_item.quantity += 1  # 如果购物车项已存在，增加数量
        cart_item.price += product.price  # 增加总价

    cart_item.save()

    # 更新购物车的总价
    cart.total_price += product.price
    cart.save()

    return redirect('main/cart.html')

main/views/payment.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.http import JsonResponse
import stripe
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
import json
import os
from django.contrib.auth.decorators import login_required
from authentication.models import User
# Create your views here.


stripe.api_key = settings.STRIPE_SECRET_KEY

def checkout(request):
    user = request.user
    user = get_object_or_404(User, pk=request.session['user_id'])
    #total = str(user.get_cart_totalprice())
    #total = total.replace('.','')
    #total = int(total)
    total = 1000
    #Here is just for smart curtains
    #total = request.GET.get('total')
    #Here is just for smart curtains
    if (request.GET.get('total')):
        total = request.GET.get('total')
    
    # Create a PaymentIntent for Card Payment with dummy amount and currency
    card_payment_intent = stripe.PaymentIntent.create(
        amount=total,
        currency="usd",
        payment_method_types=["card", "alipay", "wechat_pay"],
    )
    request.session['ongoing_amount'] = total
    return render(request, "main/checkout.html", {
        "client_secret": card_payment_intent.client_secret,
        "amount": total
    })


@csrf_exempt
@require_http_methods(["POST"])
def create_wechat_pay_payment_intent(request):
    
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            user = request.user
            #total = str(user.get_cart_totalprice())
            #total = total.replace('.','')
            #total = int(total)
            total = 1000

            # Create a PaymentIntent for WeChat Pay with dummy amount and currency
            wechat_payment_intent = stripe.PaymentIntent.create(
                amount=total,
                currency="usd",
                payment_method_types=["wechat_pay"],
                shipping={
                    'name': data['name'],
                    'address': {
                        'line1': data['address']['line1'],
                        'line2': data['address']['line2'],
                        'state': data['address']['state'],
                        'postal_code': data['address']['postal_code'],
                        'country': data['address']['country'],
                    },
                },
            )

            return JsonResponse({
                "client_secret": wechat_payment_intent.client_secret
            })

        except Exception as e:
            return JsonResponse({"error": str(e)})

    return JsonResponse({"error": "Invalid request method"})


@csrf_exempt
@require_http_methods(["POST"])
def create_alipay_payment_intent(request):
    
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            user = request.user
            #total = str(user.get_cart_totalprice())
            #total = total.replace('.','')
            #total = int(total)
            total = 1000

            # Create a PaymentIntent for Alipay with dummy amount and currency
            alipay_payment_intent = stripe.PaymentIntent.create(
                amount=total,
                currency="usd",
                payment_method_types=["alipay"],
                shipping={
                    'name': data['name'],
                    'address': {
                        'line1': data['address']['line1'],
                        'line2': data['address']['line2'],
                        'state': data['address']['state'],
                        'postal_code': data['address']['postal_code'],
                        'country': data['address']['country'],
                    },
                },
            )

            return JsonResponse({
                "client_secret": alipay_payment_intent.client_secret
            })

        except Exception as e:
            return JsonResponse({"error": str(e)})

    return JsonResponse({"error": "Invalid request method"})

def success(request):
    user = get_object_or_404(User, pk=request.session['user_id'])
    price = request.session["ongoing_amount"]
    if price == 100:
        user.status = "Premium"
    elif price == 200:
        user.status = "Premium Plus"
    user.save()
    return render(request, 'authentication/success.html',{"name":user.name})

def cancel(request):
    return render(request, 'authentication/cancel.html')

main/templates/main/ai_classification.html
{% extends "base.html" %}
{% load static %}
{% load filters %}
{% block resource %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/ai_solutions.css' %}"/> -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/sub_ai_solutions.css' %}"/> -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/smart_curtain_animation.css' %}"/> -->
{% endblock %}
{% block title %}AI Classification{% endblock %}

<style media="screen">
    * {
        margin: 0;
        padding: 0;
        list-style: none
    }

    .box {
        width: 400px;
        height: 150px;
        border: 1px solid black;
        background: #CCC;
        position: absolute;
        margin-left: -200px;
        margin-top: -75px;
        left: 50%;
        top: 50%;
        text-align: center;
        line-height: 150px;
        display: none;
    }

    .img-list {
        overflow: hidden;
    }

    .img-list li {
        float: left;
        width: 200px;
        height: 200px;
        border: 3px solid #666;
        position: relative;
        margin: 13px;
    }

    .img-list li img {
        width: 100%;
        height: 100%;
    }

    .img-list li .del-btn {
        position: absolute;
        right: 0;
        top: 0;
        display: inline;
    }
</style>

{% block nav_brand %}
<a class="navbar-brand" href="{% url 'main:index' %}" style="color: #dedede">SmartPlanting</a>
<span class="vl"></span>
{% endblock %}

{% block nav_items %}
<li class="nav-item">
    <a class="nav-link title1 active" href="{% url 'main:ai_solutions' 1 %}">AI Solutions</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle title2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Smart Home
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
        <li><a class="dropdown-item" href="{% url 'main:smart_curtain' 1 %}">Smart Curtain</a></li>
        <li><a class="dropdown-item" href="#">Sensing System</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item" href="{% url 'main:ai_classification' %}">AI Classification</a></li>
        <li><a class="dropdown-item" href="{% url 'main:aidiseasediagnose' %}">AI Disease Dignose</a></li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle title2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Forest Therapy
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
        <li><a class="dropdown-item" href="{% url 'main:virtual_reality_forest_therapy' 1 %}">Virtual Reality Forest
                Therapy</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item" href="#">Monthly Service Product</a></li>

        <li><a class="dropdown-item" href="#">International FT Tour</a></li>
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link title2" href="#">Small Farmers</a>
</li>
{% endblock %}

{% block content %}
<div class="container-fluid base-container">
    <!-- 第一行对齐 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'main:ai_solutions' 1 %}">AI Solutions</a></li>
            <li class="breadcrumb-item active" aria-current="page">AI Disease Diagnose</li>
        </ol>
    </nav>
</div>

<div class="content1">
    <div class="container-fluid base-container intro smart-curtain-intro">
        <div class="pic-upload">
            <h1 class="ai-classification-title">AI Plant Disease Diagnose</h1>
            <h3 class="ai-classification-description">Put a image of the plants here and diagnose their diseases</h3>

            <div>
                <img src="" id="img" />
                {% if userimg %}
                <img src="/media/ai_classification/{{userimg}}" id="userimg"/>
                {% endif %}
                {% if success %}
                <!-- <img alt="No picture uploaded yet" src={{ MEDIA_URL }}{{ result_path }} height="500"> -->
                <hr class="part-divider">
                <div class="result explanation">
                    <h5> This is the Diagnostic results:</h5>
                    <h6 id="Begin"> </h6>
                    {% if have_result %}
                    {% for disease in result_list %}
                    <h6 id="disease"> {{disease}} </h6>
                    {% endfor %}
                    {% elif initial %}
                    <h6 id="get_started"> Please upload an image to get started! </h6>
                    {% else %}
                    <h6 id="no_disease"> We haven't found any disease in your plant image uploaded </h6>
                    {% endif %}
                </div>
                <hr class="part-divider">
                {% else %}
                <!-- <img src="/static/img/no_image_uploaded.jpg" width="500"> -->
                <hr class="part-divider">
                <div class="result explanation">
                    <h5> This is the Diagnostic results:</h5>
                    <h6 id="Err"> {{err_msg}} </h6>
                    <h6 id="Begin"> </h6>
                </div>
                <hr class="part-divider">
                {% endif %}
            </div>

            <div>
                <form method="post" action="{% url 'main:pichandle_classification' %}" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input type="file" name="pic" id="file" /><br>
                    <script>
                        document.querySelector('#file').onchange = function () {
                            if (this.files.length) {
                                let file = this.files[0];
                                let reader = new FileReader();
                                reader.onload = function () {
                                    document.querySelector('#img').src = this.result;
                                    var err = document.getElementById('Err')
                                    if (err != null) err.innerHTML = '<h6 id="Err"> </h6>'
                                    var disease = document.getElementById('disease')
                                    if (disease != null) disease.innerHTML = '<h6 id="disease"> </h6>'
                                    var no_disease = document.getElementById('no_disease')
                                    if (no_disease != null) no_disease.innerHTML = '<h6 id="no_disease"> </h6>'
                                    var get_started = document.getElementById('get_started')
                                    if (get_started != null) get_started.innerHTML = '<h6 id="get_started"> </h6>'
                                    var userimg = document.getElementById('userimg')
                                    if (userimg != null) document.querySelector('#userimg').src = ""
                                    document.getElementById('Begin').innerHTML = '<h6 id="begin"> Now click show result!</h6>'
                                };
                                reader.readAsDataURL(file);
                            }
                        }
                    </script>
                    <input type="submit" name="shallow" id="shallow" value="Show Most Likely Results"><br>
                    <input type="submit" name="deep" id="deep" value="Show All Possible Results"><br>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    setTimeout(function () {
        document.getElementById("animation").style.display = "none";
        document.getElementById("animation2").style.display = "none";
    }, 7000);

    document.getElementById("lightness").addEventListener('input', (event) => {
        var percentage = parseInt(event.target.value);
        if (percentage < 50) {
            document.getElementById("shadow-left").style.background = "linear-gradient(" + (percentage / 2 + 90) + "deg, #333 " + (100 - percentage) + "%, transparent " + percentage + "%)";
            document.getElementById("shadow-right").style.background = "linear-gradient(" + (-(percentage / 2 + 90)) + "deg, #333 " + (100 - percentage) + "%, transparent " + percentage + "%)";
        } else {
            document.getElementById("shadow-left").style.background = "linear-gradient(" + (percentage / 2 + 90) + "deg, #333 " + (100 - percentage) + "%, transparent 0";
            document.getElementById("shadow-right").style.background = "linear-gradient(" + (-(percentage / 2 + 90)) + "deg, #333 " + (100 - percentage) + "%, transparent 0";
        }
    });
</script>
{% endblock %}

main/templates/main/cart.html
{% extends "base.html" %}
{% load static %}
{% load filters %}
{% block resource %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/consulting.css' %}"/>
{% endblock %}
{% block title %}Consulting{% endblock %}
{% block head_script %}

{% endblock %}

{% block nav_brand %}
    <a class="navbar-brand" href="{% url 'main:index' %}" style="color: #dedede">SmartPlanting</a>
    <span class="vl"></span>
{% endblock %}

{% block nav_items %}
<li class="nav-item">
    <a class="nav-link title1 active" href="{% url 'main:consulting' %}">Consulting</a>
</li>
    <a class="nav-link title2" style="margin-left: 20%;" href="{% url 'main:create_post' %}">New Post</a>
    <a class="nav-link title2" style="margin-left: 20%;" href="https://visionx.org/teams.html">Our Experts</a>
    
    
{% endblock %}

{% load tz %}

{% block content %}
<h1>Shopping Cart</h1>
<ul>
{% for item in cart_items %}
    <li>{{ item.product.name }} x{{ item.quantity }}: ${{ item.price }}</li>
{% endfor %}
</ul>
<p>Total: ${{ cart.total_price }}</p>
{% endblock %}

main/templates/main/my_plants.html
{% extends "base.html" %}
{% load static %}
{% block resource %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}"/>
	<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/> 
{% endblock %}
{% block title %}SmartPlanting{% endblock %}

{% block nav_brand %}
    <a class="navbar-brand active" href="{% url 'main:index' %}">SmartPlanting</a>
    <span class="vl hide-vl"></span><br>
{% endblock %}

{% block nav_items %}
    <li class="nav-item">
        <a class="nav-link title1" href="{% url 'main:ai_solutions' 1 %}">AI Solutions</a>
    </li>
    <li class="nav-item">
        <a class="nav-link title1" href="{% url 'main:consulting' %}">Consulting</a>
    </li>
    <li class="nav-item">
        <a class="nav-link title1" href="#">Third Party</a>
    </li>
{% endblock %}

{% block content %}
<script>
	function clickAlert() {
	  alert("Request submitted!\nOur Experts will diagnose and contact you as soon as possible!");
  }
</script>


<body style="background-color:#f5f5f5" class="font-sans antialiased text-gray-900 leading-normal tracking-wider bg-cover" >

	<br/><br/>
	<a class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-4 rounded-full" href="{% url 'main:add_plants' %}" >
		Add new plant
	</a> 
	{% for plant in object_list %}
			{% if plant.owner.name == request.session.username %}
	<div class="max-w-4xl flex items-center h-auto lg:h-screen flex-wrap mx-auto my-32 lg:my-0">
	  <!--Main Col-->
	  <div id="profile" class="w-full lg:w-3/5 rounded-lg lg:rounded-l-lg lg:rounded-r-none shadow-2xl bg-white opacity-75 mx-6 lg:mx-0">
		  <div class="p-4 md:p-12 text-center lg:text-left">
			  <!-- Image for mobile view-->
			  <div class="block lg:hidden rounded-full shadow-xl mx-auto -mt-16 h-48 w-48 bg-cover bg-center"></div>
			  <h1 class="text-3xl font-bold pt-8 lg:pt-0">{{plant.name}}</h1>
			  
			
			<br/>
			  <form action = "{% url 'main:diagnose' plant.pk %}" method="POST">
				<a class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-3 rounded-full" href="{% url 'main:manage_plants' plant.pk %}">Manage my plant</a>
				{% csrf_token %}
				<a class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-3 rounded-full" href="{% url 'main:plants_care' plant.pk %}">Plant Care</a>
				{% csrf_token %}
				<!--
					<button type="submit" class="bg-green-700 hover:bg-green-900 text-white font-bold py-1.5 px-3 rounded-full" onclick="clickAlert()">Health diagnosis</button>
				-->
				<a class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-3 rounded-full" href="{% url 'main:delete_plants' plant.pk %}">Delete</a>
				{% csrf_token %}
			 </form>
			 
			  <p class="pt-4 text-sm"> <strong>Category: </strong> {{plant.category}} </p>
			  <p class="pt-4 text-sm"> <strong>Age: </strong> {{plant.age}} years </p>
			  <p class="pt-4 text-sm"> <strong>Health Condition: </strong>{{plant.health}}</p>
			
		  </div>
		  
	  </div>
	  
	  <!--Img Col-->
	  <div class="w-full lg:w-2/5">
		<br/>
		<div style="width: 500px; height: 300px;">
		  <!-- Big profile image for side bar (desktop) -->
		  <img src="{{plant.image.url}}" style="height: 92%; width: 90%;" class="rounded-none lg:rounded-lg shadow-2xl hidden lg:block">
		  <!-- Image from: http://unsplash.com/photos/MP0IUfwrn0A -->
		  
		</div>
	  </div>
	  
  </div>
  
	  <script src="https://unpkg.com/popper.js@1/dist/umd/popper.min.js"></script>
	  <script src="https://unpkg.com/tippy.js@4"></script>
	  <script>
		  //Init tooltips
		  tippy('.link',{
			placement: 'bottom'
		  })
  
		  //Toggle mode
		  const toggle = document.querySelector('.js-change-theme');
		  const body = document.querySelector('body');
		  const profile = document.getElementById('profile');
		  
		  
		  toggle.addEventListener('click', () => {
  
			if (body.classList.contains('text-gray-900')) {
			  toggle.innerHTML = "☀️";
			  body.classList.remove('text-gray-900');
			  body.classList.add('text-gray-100');
			  profile.classList.remove('bg-white');
			  profile.classList.add('bg-gray-900');
			} else
			{
			  toggle.innerHTML = "🌙";
			  body.classList.remove('text-gray-100');
			  body.classList.add('text-gray-900');
			  profile.classList.remove('bg-gray-900');			
			  profile.classList.add('bg-white');
			  
			}
		  });
		  
	  </script>
	  
	  {%endif%}
  {%endfor%}
  </body>
{% endblock %}