authentication/urls.py
from django.urls import path

from authentication.views import user
from authentication.views.user import update_profile, upgrade
from main.views.payment import checkout
from main.views.cart import add_to_cart

app_name = 'authentication'
urlpatterns = [
    path('update/<int:pk>', update_profile.as_view(), name='update'),
    path('login/', user.login, name='login'),
    path('logout/', user.logout, name='logout'),
    path('register/', user.register, name='register'),
    path('checkcart/', user.check_cart, name='check_cart'),
    path('expert/', user.expert, name='expert'),
    path('<str:username>/', user.userinfo, name='user'),
    path('upgrade/<int:pk>', upgrade.as_view(), name='upgrade'),
    path("checkout/", checkout, name="checkout"),
]

main/urls.py
from django.urls import path
# self edited --------------------------
from django.urls import re_path
from django.views.static import serve
from mysite.settings import MEDIA_ROOT
# self edited --------------------------
from main.views import ai_solutions
from main.views.consulting import HomeView
from main.views.consulting import PostDetail
from main.views.consulting import CreatePost
from main.views.consulting import AddComment,shopping_carts
from main.views.consulting import Experts
from main.views.consulting import LikeView
from main.views.consulting import PostRate
from main.views.consulting import ReverseView
from main.views.consulting import SortedView
from main.views.consulting import HotView
from main.views.consulting import MyShare
from main.views.plant import *
from main.views.plant import my_plants
from main.views.plant import add_plants, manage_plants
from main.views.plant import diagnoseView
from main.views.plant import delete_plants
from main.views.payment import checkout
from main.views.payment import create_alipay_payment_intent
from main.views.payment import create_wechat_pay_payment_intent
from main.views.payment import success
from main.views.payment import cancel
from main.views import payment
from main.views.cart import view_cart
from main.views.cart import add_to_cart

app_name = 'main'
urlpatterns = [
    path('', ai_solutions.index, name='index'),
    path('aisolutions/<int:page>/', ai_solutions.ai_solutions, name='ai_solutions'),
    path('aisolutions/smartcurtain/<int:page>/', ai_solutions.smart_curtain, name='smart_curtain'),
    path('aisolutions/ai_classification/', ai_solutions.ai_classification, name='ai_classification'),
    path('aisolutions/aidiseasediagnose/', ai_solutions.ai_disease_diagnose, name='aidiseasediagnose'),
    path('aisolutions/aidiseasediagnose/pichandle_classification/', ai_solutions.pic_handle_classification, name='pichandle_classification'),
    path('aisolutions/aidiseasediagnose/pichandle_yolov5/', ai_solutions.pic_handle_yolov5, name='pichandle_yolov5'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': 'main/static/'}),

    path('aisolutions/virtualrealityforesttherapy/<int:page>/', ai_solutions.virtual_reality_forest_therapy, name='virtual_reality_forest_therapy'),
    path('aisolutions/virtualrealityforesttherapy/digital_twin/', ai_solutions.digital_twin, name='digital_twin'),
    path('aisolutions/virtualrealityforesttherapy/vr_detail/', ai_solutions.vr_detail, name='vr_detail'),


    #path('', HomeView.as_view(), name='index'),
    path('consulting/', HomeView.as_view(), name='consulting'),
    path('consulting/my_share', MyShare.as_view(), name='my_share'),
    path('consulting/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('consulting/creatingPost/', CreatePost.as_view(), name='create_post'),
    path('consulting/<int:pk>/commentPost/', AddComment.as_view(), name='add_comment'),
    path('consulting/experts', Experts.as_view(), name='experts'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('consulting/', ReverseView.as_view(), name='reverse_post'),
    path('consulting/sorted/', SortedView.as_view(), name='sorted_post'),
    path('consulting/hot/', HotView.as_view(), name='hot_post'),
    path('my_plants/', my_plants.as_view(), name='my_plants'),
    path('manage_plants/<int:pk>/', manage_plants.as_view(), name='manage_plants'),
    path('add_plants/', add_plants.as_view(), name='add_plants'),
    path('plants_care/<int:pk>', plants_care.as_view(), name='plants_care'),
    path('diagnose/<int:pk>', diagnoseView, name='diagnose'),
    path('delete_plants/<int:pk>', delete_plants.as_view(), name='delete_plants'),
    path('shopping_carts/', shopping_carts.as_view(), name='shopping_carts'),


    path('consulting/<int:post_id>/<int:rating>/', PostRate, name='post_rate'),
    path("checkout/", checkout, name="checkout"),
    path("checkout/create_wechat_pay_payment_intent", payment.create_wechat_pay_payment_intent, name="create_wechat_pay_payment_intent"),
    path("checkout/create_alipay_payment_intent", payment.create_alipay_payment_intent, name="create_alipay_payment_intent"),
	  path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('cart/', view_cart, name='veiw_cart'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                path('', include('main.urls')),
                path('authentication/', include('authentication.urls')),
                path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views/ai_solutions.py
from django.shortcuts import render
# self edited --------------------------
from django.conf import settings
import main.views.yolov5_optimized.detect as detect
from pathlib import Path
# self edited --------------------------

import logging

# for 3rd party AI classification API
import json
import requests
import time

from authentication.utils.check_login_state import check_login
from main.utils.ai_solutions_utils import *

logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'main/index.html')


#@check_login
def ai_solutions(request, page):
    product_list, promotion_product_list, first_promotion_product, pagination = get_product(page)

    return render(request, 'main/ai_solutions.html',
                  {'product_list': product_list, 'promotion_product_list': promotion_product_list,
                   'first_promotion_product': first_promotion_product,
                   'promotion_product_num': range(len(promotion_product_list)),
                   'pagination': pagination})

#@check_login
def ai_classification(request):
    return render(request, 'main/ai_classification.html', {"success": True, "initial": True})

#@check_login
def ai_disease_diagnose(request):
    return render(request, 'main/ai_disease_diagnose.html', {"success": True, "initial": True})

def pic_handle_classification(request):
    diseases = []
    have_result = False
    
    if request.method == "POST":
        f1 = request.FILES.get('pic')
        if f1:
            fname = settings.MEDIA_ROOT + '/ai_classification/' + f1.name
            with open(fname,'wb') as pic:
                for c in f1.chunks():
                    pic.write(c)
            try:
                response_inference = json.loads(
                    requests.post(
                        "https://api.modelplace.ai/v3/process",
                        params={"model_id": 15, },
                        files={"upload_data": open(fname, "rb")}
                    ).content
                )
                
                while True:
                    response_task = json.loads(
                        requests.get(
                            "https://api.modelplace.ai/v3/task",
                            params=response_inference
                        ).content
                    )
                    if len(response_task) == 0:
                        raise Exception("response empty!")
                    
                    if response_task.get("status", -1) == -1:
                        raise Exception("Error: Error when detecting your image! This may result from the inaccessibility of our sevice, try again later!")
                    
                    if response_task["status"] != "finished":
                        time.sleep(5)
                    else:
                        res = response_task["result"]
                        for i in range(len(res)):
                            diseases.append(res[i]["class_name"])
                        have_result = True
                        return render(request,'main/ai_classification.html', {'success':True, 'result_list': diseases, 'have_result': have_result, 'userimg': f1.name})
            except Exception as e:
                return render(request,'main/ai_classification.html', {'success':False, "err_msg": str(e), 'userimg': f1.name})
        else:
            return render(request,'main/ai_classification.html', {'success':False, "err_msg": "Error: file uploaded is empty! Please click choose file to select an image!"})
        
    return render(request,'main/ai_classification.html', {'success':True, 'result_list': diseases, 'have_result': have_result})

def pic_handle_yolov5(request):
    if request.method == "POST":
        f1 = request.FILES.get('pic')
        if f1:
            fname = settings.MEDIA_ROOT + '/aidiseasediagnose/' + f1.name
            with open(fname,'wb') as pic:
                for c in f1.chunks():
                    pic.write(c)
            try:
                if "shallow" in request.POST:
                    result_path = detect.run(weights="main/views/yolov5_optimized/16x2.pt",imgsz=(416,416),conf_thres=0.5,source=fname)
                else:
                    result_path = detect.run(weights="main/views/yolov5_optimized/16x2.pt",imgsz=(416,416),conf_thres=0.25,source=fname)
            except Exception as e:
                return render(request,'main/ai_disease_diagnose.html', {'success':False, 'err_msg': repr(e)})
        else:
            error = "file uploaded is empty"
            return render(request,'main/ai_disease_diagnose.html', {'success':False, 'err_msg': error})

        # success
        txt_path = settings.MEDIA_ROOT + "/" + result_path + "/labels/result.txt"
        path = Path(txt_path)
        diseases = []
        have_result = False
        if path.is_file():
            have_result = True
            with open (txt_path, 'r') as f:
                for line in f.readlines():
                    disease = line.split(' ')[0]
                    if disease not in diseases:
                        diseases.append(disease)

        return render(request,'main/ai_disease_diagnose.html', {'success': True, 'result_path': result_path + "/result.jpg", 'result_list': diseases, 'have_result': have_result})

    return render(request,'main/ai_disease_diagnose.html', {'success': True})
# self edited --------------------------

#@check_login
def smart_curtain(request, page):
    product_list, promotion_product_list, first_promotion_product, pagination = get_product(page)
    load_animation = False
    if page == 1:
        load_animation = True

    return render(request, 'main/smart_curtain.html',
                  {'product_list': product_list,
                   'pagination': pagination,
                   'load_animation': load_animation})

#@check_login
def virtual_reality_forest_therapy(request, page):
    product_list, VR_product_list, first_promotion_product, pagination = get_VR_FT(page)

    return render(request, 'main/virtual_reality_forest_therapy.html',
                  {'product_list': product_list, 'VR_product_list': VR_product_list,
                   'first_promotion_product': first_promotion_product,
                   'promotion_product_num': range(len(VR_product_list)),
                   'pagination': pagination})

def digital_twin(request):
    return render(request,'main/VRFT_digital_twin.html')

def vr_detail(request):
    return render(request,'main/vr_detail.html')

main/views/cart.py
from django.shortcuts import render, get_object_or_404
from main.models import Product
from django.shortcuts import redirect
from main.models import Cart, CartItem
from authentication.models import User

def view_cart(request):
    user = request.user
    #user = get_object_or_404(User, pk=request.session['user_id'])
    cart, created = Cart.objects.get_or_create(user=user, ordered=False)

    cart_items = CartItem.objects.filter(cart=cart)

    return render(request, 'main/cart.html', {
        'cart_items': cart_items,
        'cart': cart,
    })


def add_to_cart(request, slug):
    user = request.user
    #user = get_object_or_404(User, pk=request.session['user_id'])
    cart, created = Cart.objects.get_or_create(user=user, ordered=False)
    product = get_object_or_404(Product, pk=product_id)

    # 查看购物车中是否已存在该商品
    cart_item, created = CartItem.objects.get_or_create(
        user=user,
        product=product,
        cart=cart,
    )

    if created:
        cart_item.price = product.price  # 如果是新创建的购物车项，设置价格
    else:
        cart_item.quantity += 1  # 如果购物车项已存在，增加数量
        cart_item.price += product.price  # 增加总价

    cart_item.save()

    # 更新购物车的总价
    cart.total_price += product.price
    cart.save()

    return redirect('main/cart.html')

main/views/plant.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView,UpdateView,CreateView,DeleteView,DetailView
from django.core.mail import send_mail
from main.models import Plant
from authentication.models import User
from django.shortcuts import render

class my_plants(ListView):
    model = Plant
    template_name = 'main/my_plants.html'
    fields = ['name', 'category', 'age', 'image', 'health']

    def dispatch(self, request, *args, **kwargs):
        try:
            self.user = get_object_or_404(User, pk=request.session['user_id'])
        except:
            self.user = user = User.objects.get(name='Guest')
        Plant.objects.filter(owner=None).update(owner=self.user)
        return super(my_plants, self).dispatch(request, *args, **kwargs)

class add_plants(CreateView):
    model = Plant
    template_name = 'main/add_plants.html'
    fields = ['name', 'category', 'age', 'image', 'health']

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Plant.objects.order_by('id')
        return super(add_plants, self).get_context_data(**kwargs)


class delete_plants(DeleteView):
    model = Plant
    template_name = 'main/delete_plants.html'
    fields = ['name', 'category', 'age', 'image', 'health']
    success_url = reverse_lazy('main:my_plants')

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Plant.objects.order_by('id')
        return super(delete_plants, self).get_context_data(**kwargs)

class manage_plants(UpdateView):
    model = Plant
    template_name = 'main/manage_plants.html'
    fields = ['name', 'category', 'age', 'image', 'health']

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Plant.objects.order_by('id')
        return super(manage_plants, self).get_context_data(**kwargs)

class plants_care(ListView):
    model = Plant
    template_name = 'main/plant_care.html'
    fields = ['name', 'category', 'age', 'image', 'health']
    
    def get_context_data(self, **kwargs):
        kwargs['object_list'] = Plant.objects.order_by('id')
        return super(plants_care, self).get_context_data(**kwargs)

def diagnoseView(request, pk):
    plant = get_object_or_404(Plant, pk=pk)
    plant.diagnose = True
    plant.save()
    send_mail(
        "Health Diagnosis",
        f"Hello, \n\nThe user:{plant.owner.name}({plant.owner.email}) has requested the health diagnosis for '{plant.name}',\nPlease check the detail at Smartplanting.net as admin.\n\nThank you!",
        "rundi.liu26@gmail.com",
        ["rundi.liu26@visionx.org"]
    )
    return HttpResponseRedirect(reverse('main:my_plants'))

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/animejs@3.2.1/lib/anime.min.js"
            integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/noframework.waypoints.min.js"
            integrity="sha512-fHXRw0CXruAoINU11+hgqYvY/PcsOWzmj0QmcSOtjlJcqITbPyypc8cYpidjPurWpCnlB8VKfRwx6PIpASCUkQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://kit.fontawesome.com/1fb9f38c90.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <script src="{% static 'js/animation.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    {% block resource %}{% endblock %}
    <title>{% block title %}SmartPlanting{% endblock %}</title>
    {% block head_script %}{% endblock %}
</head>

<body>
<div class="header">
    <nav class="navbar-expand-lg navbar navbar-dark" style="background-color: #114934;">
        <div class="container-fluid base-container">
            {% block nav_brand %}{% endblock %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% block nav_items %}{% endblock %}
                </ul>
                <ul class="nav justify-content-end icon-group">
                    <li class="nav-item">
                        <a class="nav-link" href="#" role="button"><i
                                class="fas fa-search"></i></a>
                    </li>
                    {% if request.session.user_id %}
                        <li class="nav-item dropdown">
                            <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button"
                               data-bs-display="static"
                               aria-expanded="false"><i
                                    class="fas fa-user"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
                                <li><a class="dropdown-header"
                                       href="{% url 'authentication:user'  request.session.username %}">{{ request.session.username }}</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">My order</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:my_share' %}">My share</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'authentication:logout' %}">Log out</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button"
                               data-bs-display="static"
                               aria-expanded="false"><i class="fas fa-shopping-bag"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start cart" id="cart">
                                <li><span class="dropdown-item"><i class="fas fa-shopping-cart"></i></span></li>
                                
                                <li><a class="dropdown-item" href="/cart">Shopping Cart</a></li>

                                {#                                <li><span class="dropdown-header"><i class="fas fa-shopping-cart"></i> Cart</span></li>#}
                                {#                                <li>#}
                                {#                                    <hr class="dropdown-divider">#}
                                {#                                </li>#}
                                {#                                <li><p class="dropdown-item">Curtain x1</p></li>#}
                                {#                                <li>#}
                                {#                                    <hr class="dropdown-divider">#}
                                {#                                </li>#}
                                {#                                <li><a class="dropdown-item" href="#">Go to Cart</a></li>#}
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:login' %}"><i
                                    class="fas fa-user"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:login' %}"><i
                                    class="fas fa-shopping-bag"></i></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="content">
    {% block content %}{% endblock %}
    <div class="footer" id="footer">
        <div class="container-fluid base-container">
            <div class="row">
                <div class="col-lg footer-div footer-div-left footer-div-from-up">
                    <div class="footer-text">
                        <h1>Get In Touch</h1>
                        <p>
                            250 W Tasman Dr<br/>
                            San Jose, CA 95134<br/>
                            Phone: +1 408-418-6388<br/>
                            Fax: +1775 240 9793<br/>
                            Email: Support@visionx.org<br/>
                        </p>
                    </div>
                </div>
                <div class="col-lg footer-div footer-div-from-down">
                    <div class="footer-text">
                        <h1>About Us</h1>
                        <p>
                            Smart home is a cross-industry which focus on plant care.
                            Our company has designed and developed a set of artificial intelligence to automatically
                            identify
                            each Flowers and trees and their growth status, combined with real-time geographic and
                            climate
                            conditions, using big data analysis and timely prediction and guidance on the healthy growth
                            conditions of flowers and trees.
                        </p>
                    </div>
                </div>
                <div class="col-lg footer-div footer-div-right footer-div-from-up">
                    <div class="footer-text">
                        <h1>Join Us Now!</h1>
                        <p>
                            We are active on Twitter, <br/>
                            Telegram, Medium, Reddit, <br/>
                            YouTube, Instagram, <br/>
                            Facebook, LinkedIn, GitHub <br/>
                            and Coinmarketcap.
                        </p>
                        <div class="social-media-icon-group">
                            <ul class="social-media-icon-group-ul">
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-telegram"></i></a></li>
                                <li><a href="#"><i class="fab fa-medium"></i></a></li>
                                <li><a href="#"><i class="fab fa-reddit-alien"></i></a></li>
                                <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fab fa-github"></i></a></li>
                                <li><a href="#">
                                    <img src="{% static 'img/coinmarketcap.svg' %}" class="filter-blue"/>
                                </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright" id="footer_copyright">
        <div class="container-fluid base-container">
            <div class="row">
                <div class="col-lg footer-copyright-from-left">
                    <p>Copyright © 2020 Visionx Llc</p>
                </div>
                <div class="col-lg footer-copyright-from-right">
                    <p>Powered By <a href="https://www.visionx.org">Visionx Llc</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% block script %}{% endblock %}
</body>
</html>